import { Entries } from '../models/types'

export const squareBracketClasses: Entries = {
  opacity: 'opacity:',
  fill: 'fill:',
  text: 'text:',
  py: 'padding-top: var(--tw-padding-y) ;\npadding-bottom: var(--tw-padding-y);\n --tw-padding-y:',
  px: 'padding-left: var(--tw-padding-x) ;\npadding-right: var(--tw-padding-x);\n --tw-padding-x:',
  bg: 'background-color:',
  pr: 'padding-right:',
  pl: 'padding-left:',
  pb: 'padding-bottom:',
  pt: 'padding-top:',
  p: 'padding:',
  mr: 'margin-right:',
  ml: 'margin-left:',
  mb: 'margin-bottom:',
  mt: 'margin-top:',
  m: 'margin:',
  my: 'margin-top: var(--tw-margin-y) ;\nmargin-bottom: var(--tw-margin-y);\n --tw-margin-y:',
  mx: 'margin-left: var(--tw-margin-x) ;\nmargin-right: var(--tw-margin-x);\n --tw-margin-x:',
  top: 'top:',
  left: 'left:',
  right: 'right:',
  bottom: 'bottom:',
  h: 'height:',
  w: 'width:',
  border: 'border-width:',
  'min-h': 'min-height:',
  'max-h': 'max-height:',
  'min-w': 'min-width:',
  'max-w': 'max-width:',
  'gap-x': 'column-gap:',
  'gap-y': 'row-gap:',
  gap: 'gap:',
  outline: 'outline-width:',
  accent: 'accent-color:',
  caret: 'caret-color:',
  stroke: 'stroke-color:',
  decoration: 'text-decoration-color:',
  indent: 'text-indent:',
  leading: 'line-height:',
  z: 'z-index:',
  columns: 'columns:',
  rounded: 'border-radius:',
}
